"""Single squashed initial migration after Option A reset.
DO NOT apply on production database with existing data; this rewrite assumes a fresh schema.
Generated manually to reflect current domain_* model modules.
"""
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):
    initial = True
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Core models
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('hdid', models.AutoField(primary_key=True, serialize=False)),
                ('holiday_date', models.DateField()),
                ('holiday_name', models.CharField(max_length=255)),
                ('holiday_day', models.CharField(max_length=50)),
            ],
            options={'db_table': 'holiday'},
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('moduleid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdat')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedat')),
                ('updated_by', models.ForeignKey(blank=True, null=True, db_column='updatedby', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'api_module'},
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menuid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdat')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedat')),
                ('updated_by', models.ForeignKey(blank=True, null=True, db_column='updatedby', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(db_column='moduleid', on_delete=django.db.models.deletion.CASCADE, to='api.module')),
            ],
            options={'db_table': 'api_menu'},
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('profileid', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('social_links', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdat')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedat')),
                ('user', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'user_profiles'},
        ),
        # Additional models and fields...
    ]

# Generated by Django 5.2.3 on 2025-09-25 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('hdid', models.AutoField(primary_key=True, serialize=False)),
                ('holiday_date', models.DateField()),
                ('holiday_name', models.CharField(max_length=255)),
                ('holiday_day', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'holiday',
            },
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('institute_id', models.AutoField(primary_key=True, serialize=False)),
                ('institute_code', models.CharField(db_index=True, max_length=255, unique=True)),
                ('institute_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdat')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedat')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updatedby', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_institutes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'institute',
            },
        ),
        migrations.CreateModel(
            name='MainBranch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('maincourse_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('course_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdat')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedat')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updatedby', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main_branch',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('moduleid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdat')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedat')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updatedby', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_module',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menuid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdat')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedat')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updatedby', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(db_column='moduleid', on_delete=django.db.models.deletion.CASCADE, to='api.module')),
            ],
            options={
                'db_table': 'api_menu',
            },
        ),
        migrations.CreateModel(
            name='SubBranch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subcourse_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('subcourse_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdat')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedat')),
                ('maincourse', models.ForeignKey(db_column='maincourse_id', on_delete=django.db.models.deletion.CASCADE, related_name='sub_branches', to='api.mainbranch')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updatedby', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sub_branch',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('profileid', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('social_links', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdat')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedat')),
                ('user', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('student_name', models.CharField(db_index=True, max_length=100, verbose_name='Student Name')),
                ('batch', models.IntegerField(verbose_name='Batch')),
                ('enrollment_no', models.CharField(blank=True, db_column='enrollment_no', max_length=50, null=True, unique=True, verbose_name='Enrollment Number')),
                ('temp_enroll_no', models.CharField(blank=True, db_column='temp_enroll_no', max_length=50, null=True, verbose_name='Temporary Enrollment Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='Updated At')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('institute', models.ForeignKey(db_column='institute_id', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.institute', verbose_name='Institute')),
                ('maincourse', models.ForeignKey(db_column='maincourse_id', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.mainbranch', verbose_name='Main Course')),
                ('subcourse', models.ForeignKey(db_column='subcourse_id', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.subbranch', verbose_name='Subcourse')),
            ],
            options={
                'db_table': 'enrollment',
                'indexes': [models.Index(fields=['institute', 'subcourse', 'maincourse'], name='enrollment_institu_e42e69_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('permitid', models.AutoField(primary_key=True, serialize=False)),
                ('can_view', models.BooleanField(db_column='canview', default=False)),
                ('can_edit', models.BooleanField(db_column='canedit', default=False)),
                ('can_delete', models.BooleanField(db_column='candelete', default=False)),
                ('can_create', models.BooleanField(db_column='cancreate', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdat')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedat')),
                ('menu', models.ForeignKey(blank=True, db_column='menuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.menu')),
                ('module', models.ForeignKey(blank=True, db_column='moduleid', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.module')),
                ('user', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_userpermissions',
                'unique_together': {('user', 'module', 'menu')},
            },
        ),
    ]
