# Generated by Django 5.1.6 on 2025-02-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('hdid', models.AutoField(primary_key=True, serialize=False)),
                ('holiday_date', models.DateField()),
                ('holiday_name', models.CharField(max_length=255)),
                ('holiday_day', models.CharField(max_length=50)),
            ],
        ),
    ]
