# Generated by Django 5.1.6 on 2025-02-17 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='holiday',
            table='holiday',
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('usercode', models.CharField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('usrpassword', models.CharField(max_length=255)),
                ('usertype', models.CharField(max_length=50)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('updatedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
