# Generated by Django 5.2.3 on 2025-09-27 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Skipped adding fields that already exist in the target database to avoid duplicate column errors
        # Skipped adding 'course_code' on mainbranch because column exists already in target DB
        migrations.AlterField(
            model_name='enrollment',
            name='maincourse',
            field=models.ForeignKey(db_column='maincourse_id', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.mainbranch', to_field='maincourse_id', verbose_name='Main Course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='subcourse',
            field=models.ForeignKey(db_column='subcourse_id', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.subbranch', to_field='subcourse_id'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='institute_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subbranch',
            name='maincourse',
            field=models.ForeignKey(db_column='maincourse_id', on_delete=django.db.models.deletion.CASCADE, related_name='sub_branches', to='api.mainbranch', to_field='maincourse_id'),
        ),
        migrations.CreateModel(
            name='InstituteCourseOffering',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('campus', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdat')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedat')),
                ('institute', models.ForeignKey(db_column='institute_id', on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='api.institute')),
                ('maincourse', models.ForeignKey(db_column='maincourse_id', on_delete=django.db.models.deletion.CASCADE, related_name='institute_offerings', to='api.mainbranch', to_field='maincourse_id')),
                ('subcourse', models.ForeignKey(blank=True, db_column='subcourse_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institute_offerings', to='api.subbranch', to_field='subcourse_id')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updatedby', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'institute_course_offering',
                'indexes': [models.Index(fields=['institute', 'maincourse', 'subcourse'], name='institute_c_institu_b06a45_idx')],
            },
        ),
    ]
