# Generated by Django 5.2.3 on 2025-10-09 10:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20, unique=True)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('left_date', models.DateField(blank=True, null=True)),
                ('leave_group', models.CharField(blank=True, max_length=20, null=True)),
                ('emp_birth_date', models.DateField(blank=True, null=True)),
                ('el_balance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sl_balance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cl_balance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vacation_balance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('actual_joining', models.DateField(blank=True, null=True)),
                ('department_joining', models.CharField(blank=True, max_length=100, null=True)),
                ('institute_id', models.CharField(blank=True, max_length=50, null=True)),
                ('joining_year_allocation_el', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('joining_year_allocation_cl', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('joining_year_allocation_sl', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('joining_year_allocation_vac', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('leave_calculation_date', models.DateField(blank=True, null=True)),
                ('emp_short', models.IntegerField(blank=True, null=True)),
                ('userid', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('leave_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('leave_name', models.CharField(max_length=100)),
                ('main_type', models.CharField(blank=True, max_length=10, null=True)),
                ('day_value', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('session', models.CharField(blank=True, max_length=10, null=True)),
                ('annual_allocation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_half', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_report_no', models.CharField(blank=True, max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_by', models.CharField(blank=True, max_length=50, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('emp', models.ForeignKey(db_column='emp_id', on_delete=django.db.models.deletion.CASCADE, to='api.empprofile', to_field='emp_id')),
                ('leave_type', models.ForeignKey(db_column='leave_code', on_delete=django.db.models.deletion.CASCADE, to='api.leavetype')),
            ],
        ),
    ]
