# Generated by Django 5.1.6 on 2025-02-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_holiday_table_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updatedby',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
