# Generated by Django 5.2.3 on 2025-09-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_enrollment_admission_date_enrollment_enrollment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='institute_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='institute_campus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='institute_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mainbranch',
            name='course_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
