# Generated by Django 5.2.3 on 2025-09-29 05:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_enrollment_admission_date_enrollment_enrollment_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='date', default=django.utils.timezone.now)),
                ('student_name', models.CharField(db_column='student_name', max_length=255)),
                ('tr_count', models.PositiveSmallIntegerField(db_column='tr_count', default=0)),
                ('ms_count', models.PositiveSmallIntegerField(db_column='ms_count', default=0)),
                ('dg_count', models.PositiveSmallIntegerField(db_column='dg_count', default=0)),
                ('moi_count', models.PositiveSmallIntegerField(db_column='moi_count', default=0)),
                ('backlog_count', models.PositiveSmallIntegerField(db_column='backlog_count', default=0)),
                ('pay_rec_no', models.CharField(blank=True, db_column='pay_rec_no', max_length=100, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('CORRECTION', 'Correction'), ('CANCEL', 'Cancel'), ('DONE', 'Done')], db_column='status', default='IN_PROGRESS', max_length=20)),
                ('final_no', models.CharField(blank=True, db_column='final_no', max_length=50, null=True, unique=True)),
                ('mail_status', models.CharField(choices=[('NOT_SENT', 'Not Sent'), ('SENT', 'Sent'), ('FAILED', 'Failed')], db_column='mail_status', default='NOT_SENT', max_length=20)),
                ('eca_required', models.BooleanField(db_column='eca_required', default=False)),
                ('eca_name', models.CharField(blank=True, db_column='eca_name', max_length=255, null=True)),
                ('eca_ref_no', models.CharField(blank=True, db_column='eca_ref_no', max_length=100, null=True)),
                ('eca_submit_date', models.DateField(blank=True, db_column='eca_submit_date', null=True)),
                ('eca_mail_status', models.CharField(choices=[('NOT_SENT', 'Not Sent'), ('SENT', 'Sent'), ('FAILED', 'Failed')], db_column='eca_mail_status', default='NOT_SENT', max_length=20)),
                ('eca_resend_count', models.PositiveSmallIntegerField(db_column='eca_resend_count', default=0)),
                ('eca_last_action_at', models.DateTimeField(blank=True, db_column='eca_last_action_at', null=True)),
                ('eca_last_to_email', models.EmailField(blank=True, db_column='eca_last_to_email', max_length=254, null=True)),
                ('eca_history', models.JSONField(blank=True, db_column='eca_history', null=True)),
                ('remark', models.TextField(blank=True, db_column='remark', null=True)),
                ('last_resubmit_date', models.DateField(blank=True, db_column='last_resubmit_date', null=True)),
                ('last_resubmit_status', models.CharField(blank=True, db_column='last_resubmit_status', max_length=20, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdat')),
                ('updatedat', models.DateTimeField(auto_now=True, db_column='updatedat')),
                ('enrollment', models.ForeignKey(db_column='enrollment_id', on_delete=django.db.models.deletion.RESTRICT, related_name='verifications', to='api.enrollment')),
                ('replaces_verification', models.ForeignKey(blank=True, db_column='replaces_verification_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='api.verification')),
                ('second_enrollment', models.ForeignKey(blank=True, db_column='second_enrollment_id', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='secondary_verifications', to='api.enrollment')),
                ('updatedby', models.ForeignKey(blank=True, db_column='updatedby', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verification',
                'indexes': [models.Index(fields=['enrollment'], name='idx_verification_enrollment'), models.Index(fields=['second_enrollment'], name='idx_verif_sec_enroll'), models.Index(fields=['status'], name='idx_verification_status'), models.Index(fields=['final_no'], name='idx_verification_final_no'), models.Index(fields=['pay_rec_no'], name='idx_verification_pay_rec_no')],
                'constraints': [models.CheckConstraint(condition=models.Q(('tr_count__gte', 0), ('tr_count__lte', 999)), name='ck_tr_0_999'), models.CheckConstraint(condition=models.Q(('ms_count__gte', 0), ('ms_count__lte', 999)), name='ck_ms_0_999'), models.CheckConstraint(condition=models.Q(('dg_count__gte', 0), ('dg_count__lte', 999)), name='ck_dg_0_999'), models.CheckConstraint(condition=models.Q(('moi_count__gte', 0), ('moi_count__lte', 999)), name='ck_moi_0_999'), models.CheckConstraint(condition=models.Q(('backlog_count__gte', 0), ('backlog_count__lte', 999)), name='ck_backlog_0_999'), models.CheckConstraint(condition=models.Q(models.Q(('final_no__isnull', False), ('status', 'DONE')), models.Q(('status', 'DONE'), _negated=True), _connector='OR'), name='ck_finalno_done'), models.CheckConstraint(condition=models.Q(models.Q(('final_no__isnull', True), ('status__in', ['PENDING', 'CANCEL'])), models.Q(('status__in', ['PENDING', 'CANCEL']), _negated=True), _connector='OR'), name='ck_finalno_pending_cancel')],
            },
        ),
    ]
