# Generated by Django 5.2.3 on 2025-10-10 10:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_leaveperiod_leaveallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_date', models.DateField()),
                ('el_balance', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('sl_balance', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cl_balance', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('vacation_balance', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_snapshots', to='api.empprofile')),
            ],
            options={
                'unique_together': {('profile', 'balance_date')},
            },
        ),
    ]
