# Generated by Django 5.1.6 on 2025-02-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='createdat',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updatedat',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profilepic/default.jpg', null=True, upload_to='profilepic/'),
        ),
    ]
