# Generated by Django 5.2.3 on 2025-09-30 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_verification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPrefixRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pay_by', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('UPI', 'UPI')], db_column='pay_by', max_length=10)),
                ('year_full', models.PositiveIntegerField(blank=True, db_column='year_full', null=True)),
                ('pattern', models.CharField(db_column='pattern', max_length=50)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('priority', models.IntegerField(db_column='priority', default=0)),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdat')),
                ('updatedat', models.DateTimeField(auto_now=True, db_column='updatedat')),
            ],
            options={
                'db_table': 'pay_prefix_rule',
                'indexes': [models.Index(fields=['pay_by', 'year_full'], name='idx_payprefix_by_year'), models.Index(fields=['is_active'], name='idx_payprefix_active')],
            },
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='DocRec',
                    fields=[
                        ('id', models.BigAutoField(primary_key=True, serialize=False)),
                        ('apply_for', models.CharField(choices=[('VR', 'Verification'), ('PR', 'Provisional'), ('MG', 'Migration'), ('GT', 'Grade To Marks')], db_column='apply_for', max_length=2)),
                        ('doc_rec_id', models.CharField(db_column='doc_rec_id', max_length=20, unique=True)),
                        ('pay_by', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('UPI', 'UPI')], db_column='pay_by', max_length=10)),
                        # Adjusted to nullable to align with model refactor (facade split) keeping schema stable
                        ('pay_rec_no_pre', models.CharField(db_column='pay_rec_no_pre', max_length=20, null=True, blank=True)),
                        ('pay_rec_no', models.CharField(blank=True, db_column='pay_rec_no', max_length=50, null=True)),
                        ('pay_amount', models.DecimalField(db_column='pay_amount', decimal_places=2, default=0, max_digits=12)),
                        ('doc_rec_date', models.DateField(db_column='doc_rec_date', null=True, blank=True)),
                        ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdat')),
                        ('updatedat', models.DateTimeField(auto_now=True, db_column='updatedat')),
                        ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_recs_created', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'doc_rec',
                        'indexes': [models.Index(fields=['doc_rec_id'], name='idx_doc_rec_id'), models.Index(fields=['pay_rec_no'], name='idx_doc_pay_rec')],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
