# Generated by Django 5.2.3 on 2025-09-30 10:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_payprefixrule_docrec'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='verification',
                    name='doc_rec',
                    field=models.ForeignKey(blank=True, db_column='doc_rec_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='api.docrec', to_field='doc_rec_id'),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='verification',
                    name='vr_done_date',
                    field=models.DateField(blank=True, db_column='vr_done_date', null=True),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='verification',
                    name='backlog_count',
                    field=models.PositiveSmallIntegerField(db_column='no_of_backlog', default=0),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='verification',
                    name='date',
                    field=models.DateField(db_column='doc_rec_date', default=django.utils.timezone.now, verbose_name='Doc Record Date'),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='verification',
                    name='dg_count',
                    field=models.PositiveSmallIntegerField(db_column='no_of_degree', default=0),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='verification',
                    name='eca_mail_status',
                    field=models.CharField(choices=[('NOT_SENT', 'Not Sent'), ('SENT', 'Sent'), ('FAILED', 'Failed')], db_column='eca_status', default='NOT_SENT', max_length=20),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='verification',
                    name='mail_status',
                    field=models.CharField(choices=[('NOT_SENT', 'Not Sent'), ('SENT', 'Sent'), ('FAILED', 'Failed')], db_column='mail_send_status', default='NOT_SENT', max_length=20),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='verification',
                    name='moi_count',
                    field=models.PositiveSmallIntegerField(db_column='no_of_moi', default=0),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='verification',
                    name='ms_count',
                    field=models.PositiveSmallIntegerField(db_column='no_of_marksheet', default=0),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='verification',
                    name='remark',
                    field=models.TextField(blank=True, db_column='vr_remark', null=True),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='verification',
                    name='tr_count',
                    field=models.PositiveSmallIntegerField(db_column='no_of_transcript', default=0),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(fields=['doc_rec'], name='idx_verification_doc_rec'),
        ),
    ]
