# Generated by Django 5.2.3 on 2025-10-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_usr_birth_date_to_auth_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='empprofile',
            name='usr_birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
