# Generated by Django 5.2.3 on 2025-09-30 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_verification_doc_rec_verification_vr_done_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Eca',
                    fields=[
                        ('id', models.BigAutoField(primary_key=True, serialize=False)),
                        ('eca_name', models.CharField(blank=True, db_column='eca_name', max_length=255, null=True)),
                        ('eca_ref_no', models.CharField(blank=True, db_column='eca_ref_no', max_length=100, null=True)),
                        ('eca_send_date', models.DateField(blank=True, db_column='eca_send_date', null=True)),
                        ('eca_remark', models.TextField(blank=True, db_column='eca_remark', null=True)),
                        ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdat')),
                        ('updatedat', models.DateTimeField(auto_now=True, db_column='updatedat')),
                        ('created_by', models.ForeignKey(blank=True, db_column='createdby', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eca_created', to=settings.AUTH_USER_MODEL)),
                        ('doc_rec', models.ForeignKey(blank=True, db_column='doc_rec_id', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='eca_entries', to='api.docrec', to_field='doc_rec_id')),
                    ],
                    options={
                        'db_table': 'eca',
                        'indexes': [models.Index(fields=['doc_rec'], name='idx_eca_doc_rec')],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
