# Generated by Django 5.1.6 on 2025-03-13 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_userprofile_email_alter_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='module',
            field=models.ForeignKey(db_column='moduleid', on_delete=django.db.models.deletion.CASCADE, to='api.module'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='menu',
            field=models.ForeignKey(blank=True, db_column='menuid', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.menu'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='module',
            field=models.ForeignKey(blank=True, db_column='moduleid', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.module'),
        ),
        migrations.AlterModelTable(
            name='menu',
            table='api_menu',
        ),
        migrations.AlterModelTable(
            name='module',
            table='api_module',
        ),
        migrations.AlterModelTable(
            name='userpermission',
            table='api_userpermissions',
        ),
    ]
