# Generated by Django 5.1.6 on 2025-10-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_empprofile_usr_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaveallocation',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='leavebalancesnapshot',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='leaveentry',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='leaveperiod',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='leavetype',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='docrec',
            name='doc_rec_remark',
            field=models.TextField(blank=True, db_column='doc_rec_remark', null=True),
        ),
    ]
