# Generated by Django 5.2.3 on 2025-09-30 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_eca'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='InstVerificationMain',
                    fields=[
                        ('id', models.BigAutoField(primary_key=True, serialize=False)),
                        ('inst_veri_number', models.CharField(blank=True, db_column='inst_veri_number', max_length=100, null=True)),
                        ('inst_veri_date', models.DateField(blank=True, db_column='inst_veri_date', null=True)),
                        ('rec_inst_name', models.CharField(blank=True, db_column='rec_inst_name', max_length=255, null=True)),
                        ('rec_inst_address_1', models.CharField(blank=True, db_column='rec_inst_address_1', max_length=255, null=True)),
                        ('rec_inst_address_2', models.CharField(blank=True, db_column='rec_inst_address_2', max_length=255, null=True)),
                        ('rec_inst_location', models.CharField(blank=True, db_column='rec_inst_location', max_length=255, null=True)),
                        ('rec_inst_city', models.CharField(blank=True, db_column='rec_inst_city', max_length=255, null=True)),
                        ('rec_inst_pin', models.CharField(blank=True, db_column='rec_inst_pin', max_length=20, null=True)),
                        ('rec_inst_email', models.EmailField(blank=True, db_column='rec_inst_email', max_length=254, null=True)),
                        ('rec_by', models.CharField(blank=True, db_column='rec_by', max_length=255, null=True)),
                        ('doc_rec_date', models.DateField(blank=True, db_column='doc_rec_date', null=True)),
                        ('inst_ref_no', models.CharField(blank=True, db_column='inst_ref_no', max_length=100, null=True)),
                        ('ref_date', models.DateField(blank=True, db_column='ref_date', null=True)),
                        ('doc_rec', models.ForeignKey(blank=True, db_column='doc_rec_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inst_verifications', to='api.docrec', to_field='doc_rec_id')),
                        ('institute', models.ForeignKey(blank=True, db_column='institute_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inst_verification_main', to='api.institute')),
                    ],
                    options={
                        'db_table': 'inst_verification_main',
                        'indexes': [models.Index(fields=['doc_rec'], name='idx_ivm_doc_rec'), models.Index(fields=['institute'], name='idx_ivm_institute'), models.Index(fields=['inst_veri_number'], name='idx_ivm_veri_no')],
                    },
                ),
                migrations.CreateModel(
                    name='InstVerificationStudent',
                    fields=[
                        ('id', models.BigAutoField(primary_key=True, serialize=False)),
                        ('sr_no', models.PositiveIntegerField(blank=True, db_column='sr_no', null=True)),
                        ('student_name', models.CharField(blank=True, db_column='student_name', max_length=255, null=True)),
                        ('type_of_credential', models.CharField(blank=True, db_column='type_of_credential', max_length=50, null=True)),
                        ('month_year', models.CharField(blank=True, db_column='month_year', max_length=20, null=True)),
                        ('verification_status', models.CharField(blank=True, choices=[('IN_PROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('CORRECTION', 'Correction'), ('CANCEL', 'Cancel'), ('DONE', 'Done')], db_column='verification_status', max_length=20, null=True)),
                        ('doc_rec', models.ForeignKey(blank=True, db_column='doc_rec_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inst_verification_students', to='api.docrec', to_field='doc_rec_id')),
                        ('enrollment', models.ForeignKey(blank=True, db_column='enrollment_no', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inst_verification_students', to='api.enrollment', to_field='enrollment_no')),
                        ('institute', models.ForeignKey(blank=True, db_column='institute_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inst_verification_students', to='api.institute')),
                        ('main_course', models.ForeignKey(blank=True, db_column='main_course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inst_verification_students', to='api.mainbranch', to_field='maincourse_id')),
                        ('sub_course', models.ForeignKey(blank=True, db_column='sub_course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inst_verification_students', to='api.subbranch', to_field='subcourse_id')),
                    ],
                    options={
                        'db_table': 'inst_verification_student',
                        'indexes': [models.Index(fields=['doc_rec'], name='idx_ivs_doc_rec'), models.Index(fields=['enrollment'], name='idx_ivs_enrollment'), models.Index(fields=['institute'], name='idx_ivs_institute')],
                    },
                ),
            ],
        ),
    ]
