# Generated by Django 5.2.3 on 2025-10-01 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_instverificationmain_instverificationstudent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.CreateModel(
                    name='MigrationRecord',
                    fields=[
                        ('id', models.BigAutoField(primary_key=True, serialize=False)),
                        ('student_name', models.CharField(db_column='student_name', max_length=255)),
                        ('mg_number', models.CharField(db_column='mg_number', max_length=50, unique=True)),
                        ('mg_date', models.DateField(db_column='mg_date')),
                        ('exam_year', models.CharField(db_column='exam_year', max_length=20)),
                        ('admission_year', models.CharField(db_column='admission_year', max_length=20)),
                        ('exam_details', models.TextField(blank=True, db_column='exam_details', null=True)),
                        ('mg_status', models.CharField(choices=[('Pending', 'Pending'), ('Issued', 'Issued'), ('Cancelled', 'Cancelled')], db_column='mg_status', default='Pending', max_length=20)),
                        ('pay_rec_no', models.CharField(db_column='pay_rec_no', max_length=50)),
                        ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                        ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                        ('created_by', models.ForeignKey(blank=True, db_column='createdby', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_created', to=settings.AUTH_USER_MODEL)),
                        ('doc_rec', models.ForeignKey(db_column='doc_rec_id', on_delete=django.db.models.deletion.CASCADE, related_name='migration_records', to='api.docrec')),
                        ('enrollment', models.ForeignKey(db_column='enrollment_no', on_delete=django.db.models.deletion.CASCADE, related_name='migration_records', to='api.enrollment', to_field='enrollment_no', db_constraint=False)),
                        ('institute', models.ForeignKey(db_column='institute_id', on_delete=django.db.models.deletion.CASCADE, related_name='migration_records', to='api.institute')),
                        ('maincourse', models.ForeignKey(db_column='maincourse_id', on_delete=django.db.models.deletion.CASCADE, related_name='migration_records', to='api.mainbranch', to_field='maincourse_id')),
                        ('subcourse', models.ForeignKey(db_column='subcourse_id', on_delete=django.db.models.deletion.CASCADE, related_name='migration_records', to='api.subbranch', to_field='subcourse_id')),
                    ],
                    options={
                        'db_table': 'migration',
                        'indexes': [models.Index(fields=['doc_rec'], name='idx_mg_doc_rec'), models.Index(fields=['enrollment'], name='idx_mg_enrollment'), models.Index(fields=['institute'], name='idx_mg_institute'), models.Index(fields=['mg_number'], name='idx_mg_number')],
                    },
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='MigrationRecord',
                    fields=[
                        ('id', models.BigAutoField(primary_key=True, serialize=False)),
                        ('student_name', models.CharField(db_column='student_name', max_length=255)),
                        ('mg_number', models.CharField(db_column='mg_number', max_length=50, unique=True)),
                        ('mg_date', models.DateField(db_column='mg_date')),
                        ('exam_year', models.CharField(db_column='exam_year', max_length=20)),
                        ('admission_year', models.CharField(db_column='admission_year', max_length=20)),
                        ('exam_details', models.TextField(blank=True, db_column='exam_details', null=True)),
                        ('mg_status', models.CharField(choices=[('Pending', 'Pending'), ('Issued', 'Issued'), ('Cancelled', 'Cancelled')], db_column='mg_status', default='Pending', max_length=20)),
                        ('pay_rec_no', models.CharField(db_column='pay_rec_no', max_length=50)),
                        ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                        ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                        ('created_by', models.ForeignKey(blank=True, db_column='createdby', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_created', to=settings.AUTH_USER_MODEL)),
                        ('doc_rec', models.ForeignKey(db_column='doc_rec_id', on_delete=django.db.models.deletion.CASCADE, related_name='migration_records', to='api.docrec')),
                        ('enrollment', models.ForeignKey(db_column='enrollment_no', on_delete=django.db.models.deletion.CASCADE, related_name='migration_records', to='api.enrollment', to_field='enrollment_no', db_constraint=False)),
                        ('institute', models.ForeignKey(db_column='institute_id', on_delete=django.db.models.deletion.CASCADE, related_name='migration_records', to='api.institute')),
                        ('maincourse', models.ForeignKey(db_column='maincourse_id', on_delete=django.db.models.deletion.CASCADE, related_name='migration_records', to='api.mainbranch', to_field='maincourse_id')),
                        ('subcourse', models.ForeignKey(db_column='subcourse_id', on_delete=django.db.models.deletion.CASCADE, related_name='migration_records', to='api.subbranch', to_field='subcourse_id')),
                    ],
                    options={
                        'db_table': 'migration',
                        'indexes': [models.Index(fields=['doc_rec'], name='idx_mg_doc_rec'), models.Index(fields=['enrollment'], name='idx_mg_enrollment'), models.Index(fields=['institute'], name='idx_mg_institute'), models.Index(fields=['mg_number'], name='idx_mg_number')],
                    },
                ),
            ],
        ),
    ]
