# Generated by Django 5.2.3 on 2025-10-01 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_migrationrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisionalRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(db_column='student_name', max_length=255)),
                ('class_obtain', models.CharField(blank=True, db_column='class_obtain', max_length=100, null=True)),
                ('prv_number', models.CharField(db_column='prv_number', max_length=50, unique=True)),
                ('prv_date', models.DateField(db_column='prv_date')),
                ('passing_year', models.CharField(db_column='passing_year', max_length=20)),
                ('prv_status', models.CharField(choices=[('Pending', 'Pending'), ('Issued', 'Issued'), ('Cancelled', 'Cancelled')], db_column='prv_status', default='Pending', max_length=20)),
                ('pay_rec_no', models.CharField(db_column='pay_rec_no', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('created_by', models.ForeignKey(blank=True, db_column='createdby', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisional_created', to=settings.AUTH_USER_MODEL)),
                ('doc_rec', models.ForeignKey(db_column='doc_rec_id', on_delete=django.db.models.deletion.CASCADE, related_name='provisional_records', to='api.docrec')),
                ('enrollment', models.ForeignKey(db_column='enrollment_no', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='provisional_records', to='api.enrollment', to_field='enrollment_no')),
                ('institute', models.ForeignKey(db_column='institute_id', on_delete=django.db.models.deletion.CASCADE, related_name='provisional_records', to='api.institute')),
                ('maincourse', models.ForeignKey(db_column='maincourse_id', on_delete=django.db.models.deletion.CASCADE, related_name='provisional_records', to='api.mainbranch', to_field='maincourse_id')),
                ('subcourse', models.ForeignKey(db_column='subcourse_id', on_delete=django.db.models.deletion.CASCADE, related_name='provisional_records', to='api.subbranch', to_field='subcourse_id')),
            ],
            options={
                'db_table': 'provisional',
                'indexes': [models.Index(fields=['doc_rec'], name='idx_prv_doc_rec'), models.Index(fields=['enrollment'], name='idx_prv_enrollment'), models.Index(fields=['institute'], name='idx_prv_institute'), models.Index(fields=['prv_number'], name='idx_prv_number')],
            },
        ),
    ]
