# Generated by Django 5.2.3 on 2025-10-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_provisionalrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docrec',
            name='apply_for',
            field=models.CharField(choices=[('VR', 'Verification'), ('IV', 'Institutional Verification'), ('PR', 'Provisional'), ('MG', 'Migration'), ('GT', 'Grade To Marks')], db_column='apply_for', max_length=2),
        ),
    ]
