# Generated by Django 5.2.3 on 2025-10-01 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_docrec_apply_for'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(blank=True, db_column='gender', max_length=20, null=True)),
                ('birth_date', models.DateField(blank=True, db_column='birth_date', null=True)),
                ('address1', models.CharField(blank=True, db_column='address1', max_length=255, null=True)),
                ('address2', models.CharField(blank=True, db_column='address2', max_length=255, null=True)),
                ('city', models.CharField(blank=True, db_column='city', max_length=100, null=True)),
                ('state', models.CharField(blank=True, db_column='state', max_length=100, null=True)),
                ('pin_code', models.CharField(blank=True, db_column='pin_code', max_length=20, null=True)),
                ('contact_no', models.CharField(blank=True, db_column='contact_no', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, db_column='email', max_length=254, null=True)),
                ('fees', models.DecimalField(blank=True, db_column='fees', decimal_places=2, default=0, max_digits=12, null=True)),
                ('hostel_required', models.BooleanField(db_column='hostel_required', default=False)),
                ('aadhar_no', models.CharField(blank=True, db_column='aadhar_no', max_length=20, null=True)),
                ('abc_id', models.CharField(blank=True, db_column='abc_id', max_length=50, null=True)),
                ('photo_uploaded', models.BooleanField(db_column='photo_uploaded', default=False)),
                ('is_d2d', models.BooleanField(db_column='is_d2d', default=False)),
                ('program_medium', models.CharField(blank=True, db_column='program_medium', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('enrollment', models.OneToOneField(db_column='enrollment_no', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='api.enrollment', to_field='enrollment_no')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_student_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_profile',
                'indexes': [models.Index(fields=['enrollment'], name='idx_sp_enrollment')],
            },
        ),
    ]
