# Generated by Django 5.1.6 on 2025-03-13 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_menu_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdat'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedat'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='user',
            field=models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
