# Generated by Django 5.2.3 on 2025-10-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_studentprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='state',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='category',
            field=models.CharField(blank=True, db_column='category', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='city1',
            field=models.CharField(blank=True, db_column='city1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='city2',
            field=models.CharField(blank=True, db_column='city2', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mobile_adhar',
            field=models.CharField(blank=True, db_column='mobile_adhar', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_name',
            field=models.CharField(blank=True, db_column='mother_name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='name_adhar',
            field=models.CharField(blank=True, db_column='name_adhar', max_length=255, null=True),
        ),
    ]
