# Generated by Django 5.2.3 on 2025-10-03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_remove_studentprofile_city_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                """
                -- Ensure expected columns exist on user_profiles
                ALTER TABLE user_profiles
                    ADD COLUMN IF NOT EXISTS bio text,
                    ADD COLUMN IF NOT EXISTS social_links jsonb,
                    ADD COLUMN IF NOT EXISTS profile_picture varchar(100);
                """
            ),
            reverse_sql=(
                """
                -- Optional reverse: drop columns if present
                ALTER TABLE user_profiles
                    DROP COLUMN IF EXISTS bio,
                    DROP COLUMN IF EXISTS social_links,
                    DROP COLUMN IF EXISTS profile_picture;
                """
            ),
        ),
    ]
