# Generated by Django 5.2.3 on 2025-10-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_ver_status_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verification',
            old_name='eca_mail_status',
            new_name='eca_status',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='eca_history',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='eca_last_action_at',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='eca_last_to_email',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='eca_resend_count',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='eca_submit_date',
        ),
        migrations.AddField(
            model_name='verification',
            name='eca_resubmit_date',
            field=models.DateField(blank=True, db_column='eca_resubmit_date', null=True),
        ),
        migrations.AddField(
            model_name='verification',
            name='eca_send_date',
            field=models.DateField(blank=True, db_column='eca_send_date', null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='status',
            field=models.CharField(blank=True, choices=[('IN_PROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('CORRECTION', 'Correction'), ('CANCEL', 'Cancel'), ('DONE', 'Done')], db_column='status', max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='leaveallocation',
            table='leavea_llocation_general',
        ),
        migrations.AlterModelTable(
            name='leavebalancesnapshot',
            table='leave_balances',
        ),
        migrations.AlterModelTable(
            name='leaveentry',
            table='leave_entry',
        ),
        migrations.AlterModelTable(
            name='leaveperiod',
            table='leave_period',
        ),
        migrations.AlterModelTable(
            name='leavetype',
            table='leave_type',
        ),
    ]
