# Generated by Django 5.1.6 on 2025-03-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_userpermission_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='can_create',
            field=models.BooleanField(db_column='cancreate', default=False),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_delete',
            field=models.BooleanField(db_column='candelete', default=False),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_edit',
            field=models.BooleanField(db_column='canedit', default=False),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_view',
            field=models.BooleanField(db_column='canview', default=False),
        ),
    ]
