# Generated by Django 5.2.3 on 2025-10-27 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_eca_mail_status_verification_eca_status_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "ALTER TABLE migration ADD COLUMN IF NOT EXISTS doc_rec_remark VARCHAR(255);",
                    migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='migrationrecord',
                    name='doc_rec_remark',
                    field=models.CharField(blank=True, db_column='doc_rec_remark', max_length=255, null=True),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "ALTER TABLE provisional ADD COLUMN IF NOT EXISTS doc_rec_remark VARCHAR(255);",
                    migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='provisionalrecord',
                    name='doc_rec_remark',
                    field=models.CharField(blank=True, db_column='doc_rec_remark', max_length=255, null=True),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "ALTER TABLE verification ADD COLUMN IF NOT EXISTS doc_rec_remark TEXT;",
                    migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='verification',
                    name='doc_rec_remark',
                    field=models.TextField(blank=True, db_column='doc_rec_remark', null=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='docrec',
            name='doc_rec_remark',
            field=models.CharField(blank=True, db_column='doc_rec_remark', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='migrationrecord',
            name='institute',
            field=models.ForeignKey(blank=True, db_column='institute_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='migration_records', to='api.institute'),
        ),
        migrations.AlterField(
            model_name='migrationrecord',
            name='maincourse',
            field=models.ForeignKey(blank=True, db_column='maincourse_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='migration_records', to='api.mainbranch', to_field='maincourse_id'),
        ),
        migrations.AlterField(
            model_name='migrationrecord',
            name='subcourse',
            field=models.ForeignKey(blank=True, db_column='subcourse_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='migration_records', to='api.subbranch', to_field='subcourse_id'),
        ),
        migrations.AlterField(
            model_name='provisionalrecord',
            name='institute',
            field=models.ForeignKey(blank=True, db_column='institute_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provisional_records', to='api.institute'),
        ),
        migrations.AlterField(
            model_name='provisionalrecord',
            name='maincourse',
            field=models.ForeignKey(blank=True, db_column='maincourse_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provisional_records', to='api.mainbranch', to_field='maincourse_id'),
        ),
        migrations.AlterField(
            model_name='provisionalrecord',
            name='subcourse',
            field=models.ForeignKey(blank=True, db_column='subcourse_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provisional_records', to='api.subbranch', to_field='subcourse_id'),
        ),
    ]
