# Generated by Django 5.2.3 on 2025-10-03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_userprofile_add_missing_columns"),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                """
                ALTER TABLE doc_rec
                    ADD COLUMN IF NOT EXISTS doc_rec_date date;
                ALTER TABLE doc_rec
                    ALTER COLUMN pay_rec_no_pre DROP NOT NULL;
                """
            ),
            reverse_sql=(
                """
                -- No-op reverse to avoid dropping data
                SELECT 1;
                """
            ),
        ),
    ]
