# Generated by Django 5.1.6 on 2025-03-21 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_userpermission_can_create_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('institute_id', models.AutoField(primary_key=True, serialize=False)),
                ('institute_code', models.CharField(max_length=255, unique=True)),
                ('institute_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdat')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedat')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updatedby', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'institute',
            },
        ),
        migrations.CreateModel(
            name='MainBranch',
            fields=[
                ('maincourse_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=255, unique=True)),
                ('course_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdat')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedat')),
                ('institute', models.ForeignKey(db_column='institute_id', on_delete=django.db.models.deletion.CASCADE, to='api.institute')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updatedby', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main_branch',
            },
        ),
        migrations.CreateModel(
            name='SubBranch',
            fields=[
                ('subcourse_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('subcourse_code', models.CharField(max_length=255, unique=True)),
                ('subcourse_name', models.CharField(max_length=255)),
                ('created_at', models.TimeField(auto_now_add=True, db_column='createdat')),
                ('updated_at', models.TimeField(auto_now=True, db_column='updatedat')),
                ('maincourse', models.ForeignKey(db_column='maincourse_id', on_delete=django.db.models.deletion.CASCADE, to='api.mainbranch')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updatedby', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sub_branch',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_no', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=255)),
                ('batch', models.IntegerField()),
                ('enrollment_date', models.DateTimeField(auto_now_add=True, db_column='enrollment_date')),
                ('admission_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdat')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedat')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updatedby', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('institute', models.ForeignKey(db_column='institute_id', on_delete=django.db.models.deletion.CASCADE, to='api.institute')),
                ('maincourse', models.ForeignKey(db_column='maincourse_id', on_delete=django.db.models.deletion.CASCADE, to='api.mainbranch')),
                ('subcourse', models.ForeignKey(db_column='subcourse_id', on_delete=django.db.models.deletion.CASCADE, to='api.subbranch')),
            ],
            options={
                'db_table': 'enrollment',
            },
        ),
    ]
