# Generated by Django 5.2.3 on 2025-10-04 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_docrec_add_doc_rec_date_and_nullable_prefix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='verification',
            name='ck_tr_0_999',
        ),
        migrations.RemoveConstraint(
            model_name='verification',
            name='ck_ms_0_999',
        ),
        migrations.RemoveConstraint(
            model_name='verification',
            name='ck_dg_0_999',
        ),
        migrations.RemoveConstraint(
            model_name='verification',
            name='ck_moi_0_999',
        ),
        migrations.RemoveConstraint(
            model_name='verification',
            name='ck_backlog_0_999',
        ),
        migrations.RemoveConstraint(
            model_name='verification',
            name='ck_finalno_done',
        ),
        migrations.RemoveConstraint(
            model_name='verification',
            name='ck_finalno_pending_cancel',
        ),
        migrations.AlterField(
            model_name='docrec',
            name='pay_by',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('UPI', 'UPI'), ('NA', 'Not Applicable')], db_column='pay_by', max_length=10),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='batch',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_no',
            field=models.CharField(blank=True, db_column='enrollment_no', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='institute',
            field=models.ForeignKey(db_column='institute_id', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.institute'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='maincourse',
            field=models.ForeignKey(db_column='maincourse_id', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.mainbranch', to_field='maincourse_id'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='temp_enroll_no',
            field=models.CharField(blank=True, db_column='temp_enroll_no', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payprefixrule',
            name='pay_by',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('UPI', 'UPI'), ('NA', 'Not Applicable')], db_column='pay_by', max_length=10),
        ),
    ]
