# Generated by Django 5.2.3 on 2025-10-27 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_migrationrecord_doc_rec_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationrecord',
            name='admission_year',
            field=models.CharField(blank=True, db_column='admission_year', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='migrationrecord',
            name='enrollment',
            field=models.ForeignKey(blank=True, db_column='enrollment_no', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_records', to='api.enrollment', to_field='enrollment_no'),
        ),
        migrations.AlterField(
            model_name='migrationrecord',
            name='exam_year',
            field=models.CharField(blank=True, db_column='exam_year', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='migrationrecord',
            name='mg_date',
            field=models.DateField(blank=True, db_column='mg_date', null=True),
        ),
        migrations.AlterField(
            model_name='migrationrecord',
            name='pay_rec_no',
            field=models.CharField(blank=True, db_column='pay_rec_no', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='migrationrecord',
            name='student_name',
            field=models.CharField(blank=True, db_column='student_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='verification',
            name='student_name',
            field=models.CharField(blank=True, db_column='student_name', max_length=255),
        ),
    ]
