# Generated by Django 5.1.6 on 2025-03-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_institute_mainbranch_subbranch_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_no',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='institute',
            name='institute_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
