# Generated by Django 5.2.3 on 2025-10-28 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_migrationrecord_admission_year_and_more'),
    ]

    operations = [
        # Field 'prv_degree_name' already exists in the database; skip AddField to avoid duplicate column errors.
        migrations.AlterField(
            model_name='provisionalrecord',
            name='enrollment',
            field=models.ForeignKey(blank=True, db_column='enrollment_no', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisional_records', to='api.enrollment', to_field='enrollment_no'),
        ),
        migrations.AlterField(
            model_name='provisionalrecord',
            name='passing_year',
            field=models.CharField(blank=True, db_column='passing_year', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='provisionalrecord',
            name='pay_rec_no',
            field=models.CharField(blank=True, db_column='pay_rec_no', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='provisionalrecord',
            name='prv_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Issued', 'Issued'), ('Cancelled', 'Cancelled')], db_column='prv_status', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='provisionalrecord',
            name='student_name',
            field=models.CharField(blank=True, db_column='student_name', max_length=255, null=True),
        ),
    ]
