# Generated by Django 5.2.3 on 2025-10-04 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_verification_ck_tr_0_999_and_more'),
    ]

    operations = [
    ]
