# Generated by Django 5.1.6 on 2025-03-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_enrollment_enrollment_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='temp_no',
            field=models.CharField(blank=True, db_column='temp_no', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_no',
            field=models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
