# Generated by Django 5.2.3 on 2025-10-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_provisionalrecord_prv_degree_name_and_more'),
    ]

    operations = [
        # Column 'prv_degree_name' already exists in the database (manually added earlier).
        # The AddField operation is skipped to avoid DuplicateColumn errors.
        migrations.AlterField(
            model_name='migrationrecord',
            name='doc_rec',
            field=models.CharField(blank=True, db_column='doc_rec_id', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='provisionalrecord',
            name='doc_rec',
            field=models.CharField(blank=True, db_column='doc_rec_id', max_length=100, null=True),
        ),
    ]
