# Generated by Django 5.2.3 on 2025-10-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_provisionalrecord_prv_degree_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionalrecord',
            name='prv_degree_name',
            field=models.CharField(blank=True, db_column='prv_degree_name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='migrationrecord',
            name='doc_rec',
            field=models.CharField(blank=True, db_column='doc_rec_id', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='provisionalrecord',
            name='doc_rec',
            field=models.CharField(blank=True, db_column='doc_rec_id', max_length=100, null=True),
        ),
    ]
