# Generated by Django 5.1.6 on 2025-03-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_enrollment_temp_no_alter_enrollment_enrollment_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subbranch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdat'),
        ),
        migrations.AlterField(
            model_name='subbranch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedat'),
        ),
    ]
