# Generated by Django 5.1.6 on 2025-03-27 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_subbranch_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='institute',
            field=models.ForeignKey(db_column='institute_id', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.institute'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='maincourse',
            field=models.ForeignKey(db_column='maincourse_id', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.mainbranch'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='subcourse',
            field=models.ForeignKey(db_column='subcourse_id', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.subbranch'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updatedby', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='institute',
            name='institute_code',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updatedby', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_institutes', to=settings.AUTH_USER_MODEL),
        ),
    ]
