# Generated by Django 5.1.6 on 2025-09-22 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_enrollment_institute_and_more'),
    ]

    operations = [
    ]
