# Generated by Django 5.2.3 on 2025-11-03 04:28

from django.db import migrations


def noop(apps, schema_editor):
    # This migration was autogenerated but the relevant columns are already
    # present (either added manually or by a previous safe migration). Keep
    # a no-op so migration history advances without altering the DB schema.
    return


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_add_iv_degree_name'),
    ]

    operations = [
        migrations.RunPython(noop, reverse_code=noop),
    ]
