# Generated by Django 5.1.6 on 2025-09-22 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20250922_1039'),
    ]

    operations = [
    ]
