# Generated by Django 5.2.3 on 2025-09-23 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20250922_1047'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='admission_date',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='enrollment_date',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='temp_no',
        ),
        migrations.RemoveField(
            model_name='mainbranch',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='mainbranch',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='subbranch',
            name='subcourse_code',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='temp_enroll_no',
            field=models.CharField(blank=True, db_column='temp_enroll_no', max_length=50, null=True, verbose_name='Temporary Enrollment Number'),
        ),
        migrations.AddField(
            model_name='mainbranch',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='subbranch',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='batch',
            field=models.IntegerField(verbose_name='Batch'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_no',
            field=models.CharField(blank=True, db_column='enrollment_no', max_length=50, null=True, unique=True, verbose_name='Enrollment Number'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='institute',
            field=models.ForeignKey(db_column='institute_id', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.institute', verbose_name='Institute'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='maincourse',
            field=models.ForeignKey(db_column='maincourse_id', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.mainbranch', verbose_name='Main Course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Student Name'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='subcourse',
            field=models.ForeignKey(db_column='subcourse_id', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.subbranch', verbose_name='Subcourse'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='mainbranch',
            name='course_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mainbranch',
            name='maincourse_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subbranch',
            name='maincourse',
            field=models.ForeignKey(db_column='maincourse_id', on_delete=django.db.models.deletion.CASCADE, related_name='sub_branches', to='api.mainbranch'),
        ),
        migrations.AlterField(
            model_name='subbranch',
            name='subcourse_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subbranch',
            name='subcourse_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['institute', 'subcourse', 'maincourse'], name='enrollment_institu_e42e69_idx'),
        ),
    ]
