# Generated by Django 5.2.3 on 2025-11-03 04:33

from django.db import migrations


def noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_instverificationstudent_enrollment_no_text'),
    ]

    operations = [
        migrations.RunPython(noop, reverse_code=noop),
    ]
