# Generated by Django 5.2.3 on 2025-11-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_instverificationstudent_enrollment_no_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instverificationstudent',
            name='enrollment_no_text',
            field=models.CharField(blank=True, db_column='enrollment_no_text', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='instverificationstudent',
            name='iv_degree_name',
            field=models.CharField(blank=True, db_column='iv_degree_name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provisionalrecord',
            name='prv_degree_name',
            field=models.CharField(blank=True, db_column='prv_degree_name', max_length=255, null=True),
        ),
    ]
