# Generated by Django 5.2.3 on 2025-11-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_add_iv_record_no'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- add columns if they do not already exist
                        DO $$
                        BEGIN
                            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'inst_verification_main') THEN
                                ALTER TABLE inst_verification_main ADD COLUMN IF NOT EXISTS doc_types varchar(255);
                                ALTER TABLE inst_verification_main ADD COLUMN IF NOT EXISTS iv_record_no integer;
                                ALTER TABLE inst_verification_main ADD COLUMN IF NOT EXISTS iv_status varchar(20);
                                ALTER TABLE inst_verification_main ADD COLUMN IF NOT EXISTS rec_inst_sfx_name varchar(255);
                                ALTER TABLE inst_verification_main ADD COLUMN IF NOT EXISTS study_mode varchar(1);
                                CREATE INDEX IF NOT EXISTS idx_ivm_record_no ON inst_verification_main (iv_record_no);
                            END IF;
                        END $$;
                        DO $$
                        BEGIN
                            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'inst_verification_student') THEN
                                ALTER TABLE inst_verification_student ADD COLUMN IF NOT EXISTS enrollment_no_text varchar(64);
                                ALTER TABLE inst_verification_student ADD COLUMN IF NOT EXISTS iv_degree_name varchar(255);
                            END IF;
                        END $$;
                        DO $$
                        BEGIN
                            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'provisional_record') THEN
                                ALTER TABLE provisional_record ADD COLUMN IF NOT EXISTS prv_degree_name varchar(255);
                            END IF;
                        END $$;
            """,
            reverse_sql="""
            -- reverse: drop columns and index if exist
                        DO $$
                        BEGIN
                            IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'idx_ivm_record_no') THEN
                                DROP INDEX IF EXISTS idx_ivm_record_no;
                            END IF;
                        END $$;
                        DO $$
                        BEGIN
                            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'inst_verification_main') THEN
                                ALTER TABLE inst_verification_main DROP COLUMN IF EXISTS doc_types;
                                ALTER TABLE inst_verification_main DROP COLUMN IF EXISTS iv_record_no;
                                ALTER TABLE inst_verification_main DROP COLUMN IF EXISTS iv_status;
                                ALTER TABLE inst_verification_main DROP COLUMN IF EXISTS rec_inst_sfx_name;
                                ALTER TABLE inst_verification_main DROP COLUMN IF EXISTS study_mode;
                            END IF;
                        END $$;
                        DO $$
                        BEGIN
                            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'inst_verification_student') THEN
                                ALTER TABLE inst_verification_student DROP COLUMN IF EXISTS enrollment_no_text;
                                ALTER TABLE inst_verification_student DROP COLUMN IF EXISTS iv_degree_name;
                            END IF;
                        END $$;
                        DO $$
                        BEGIN
                            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'provisional_record') THEN
                                ALTER TABLE provisional_record DROP COLUMN IF EXISTS prv_degree_name;
                            END IF;
                        END $$;
            """,
        ),
    ]
