# Generated by Django 5.2.3 on 2025-11-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_instverificationmain_doc_types_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='instverificationmain',
                    name='doc_types',
                    field=models.CharField(blank=True, db_column='doc_types', max_length=255, null=True),
                ),
                migrations.AddField(
                    model_name='instverificationmain',
                    name='iv_record_no',
                    field=models.IntegerField(blank=True, db_column='iv_record_no', db_index=True, null=True),
                ),
                migrations.AddField(
                    model_name='instverificationmain',
                    name='iv_status',
                    field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Correction', 'Correction'), ('Post', 'Post'), ('Mail', 'Mail')], db_column='iv_status', max_length=20, null=True),
                ),
                migrations.AddField(
                    model_name='instverificationmain',
                    name='rec_inst_sfx_name',
                    field=models.CharField(blank=True, db_column='rec_inst_sfx_name', max_length=255, null=True),
                ),
                migrations.AddField(
                    model_name='instverificationmain',
                    name='study_mode',
                    field=models.CharField(blank=True, db_column='study_mode', max_length=1, null=True),
                ),
                migrations.AddField(
                    model_name='instverificationstudent',
                    name='enrollment_no_text',
                    field=models.CharField(blank=True, db_column='enrollment_no_text', max_length=64, null=True),
                ),
                migrations.AddField(
                    model_name='instverificationstudent',
                    name='iv_degree_name',
                    field=models.CharField(blank=True, db_column='iv_degree_name', max_length=255, null=True),
                ),
                migrations.AddField(
                    model_name='provisionalrecord',
                    name='prv_degree_name',
                    field=models.CharField(blank=True, db_column='prv_degree_name', max_length=255, null=True),
                ),
                migrations.AddIndex(
                    model_name='instverificationmain',
                    index=models.Index(fields=['iv_record_no'], name='idx_ivm_record_no'),
                ),
            ],
        ),
    ]
