# Generated by Django 5.2.3 on 2025-11-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_instverificationmain_doc_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instverificationstudent',
            name='verification_status',
            field=models.CharField(blank=True, choices=[('IN_PROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('CORRECTION', 'Correction'), ('CANCEL', 'Cancel'), ('DONE', 'Done')], db_column='verification_status', max_length=100, null=True),
        ),
    ]
