# Generated by Django 5.1.6 on 2025-11-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_instverificationstudent_verification_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(db_column='timestamp')),
                ('enrollment_no', models.CharField(blank=True, db_column='enrollment_no', max_length=64)),
                ('student_name', models.CharField(blank=True, db_column='student_name', max_length=255)),
                ('rec_institute_name', models.CharField(blank=True, db_column='rec_institute_name', max_length=512)),
                ('rec_official_mail', models.CharField(blank=True, db_column='rec_official_mail', max_length=255)),
                ('rec_ref_id', models.CharField(blank=True, db_column='rec_ref_id', max_length=128)),
                ('send_doc_type', models.CharField(blank=True, db_column='send_doc_type', max_length=255)),
                ('form_submit_mail', models.CharField(blank=True, db_column='form_submit_mail', max_length=255)),
                ('mail_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('progress', 'Progress'), ('done', 'Done')], db_column='mail_status', default='pending', max_length=32)),
                ('remark', models.TextField(blank=True, db_column='remark')),
                ('student_verification', models.CharField(blank=True, db_column='student_verification', max_length=255)),
                ('raw_row', models.JSONField(blank=True, db_column='raw_row', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created')),
            ],
            options={
                'db_table': 'google_form_submission',
                'indexes': [models.Index(fields=['submitted_at'], name='idx_gfs_submitted_at'), models.Index(fields=['enrollment_no'], name='idx_gfs_enrollment')],
            },
        ),
    ]
