# Generated by Django 5.1.6 on 2025-11-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_googleformsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(db_column='trn_reqest_date')),
                ('request_ref_no', models.CharField(blank=True, db_column='trn_reqest_ref_no', max_length=128)),
                ('enrollment_no', models.CharField(blank=True, db_column='enrollment_no', max_length=64)),
                ('student_name', models.CharField(blank=True, db_column='student_name', max_length=255)),
                ('institute_name', models.CharField(blank=True, db_column='institute_name', max_length=255)),
                ('transcript_receipt', models.CharField(blank=True, db_column='trnscript_receipt', max_length=255)),
                ('transcript_remark', models.TextField(blank=True, db_column='transcript_remark')),
                ('submit_mail', models.CharField(blank=True, db_column='submit_mail', max_length=255)),
                ('pdf_generate', models.CharField(blank=True, db_column='pdf_generate', max_length=64)),
                ('mail_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('progress', 'In Progress'), ('done', 'Done')], db_column='mail_status', default='pending', max_length=32)),
                ('raw_row', models.JSONField(blank=True, db_column='raw_row', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created')),
            ],
            options={
                'db_table': 'transcript_request',
                'indexes': [models.Index(fields=['requested_at'], name='idx_transcript_requested_at'), models.Index(fields=['enrollment_no'], name='idx_transcript_enrollment')],
            },
        ),
    ]
