# Generated by Django 5.2.3 on 2025-11-11 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_empprofile_username_usercode'),
    ]

    operations = [
        # Some deployments may already have removed 'userid' or never had it
        # (legacy schemas vary). Use a conditional SQL drop so migration is
        # idempotent and won't fail when the column is missing.
        migrations.RunSQL(
            sql="""
                ALTER TABLE api_empprofile
                DROP COLUMN IF EXISTS userid;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterModelTable(
            name='leaveallocation',
            table='api_leaveallocation',
        ),
        migrations.AlterModelTable(
            name='leavebalancesnapshot',
            table='api_leavebalancesnapshot',
        ),
        migrations.AlterModelTable(
            name='leaveentry',
            table='api_leaveentry',
        ),
        migrations.AlterModelTable(
            name='leaveperiod',
            table='api_leaveperiod',
        ),
        migrations.AlterModelTable(
            name='leavetype',
            table='api_leavetype',
        ),
    ]
