# backend/api/migrations/0033_remove_empprofile_userid.py
# Generated by Django 5.2.3 on 2025-11-12 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_empprofile_userid_alter_leaveallocation_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empprofile',
            name='userid',
        ),
    ]
