# Generated by Django 5.2.3 on 2025-11-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_empprofile_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptrequest',
            name='tr_request_no',
            field=models.BigIntegerField(blank=True, db_column='tr_request_no', null=True),
        ),
        migrations.AddIndex(
            model_name='transcriptrequest',
            index=models.Index(fields=['tr_request_no'], name='idx_transcript_tr_request_no'),
        ),
    ]
