# Generated by Django 5.2.3 on 2025-11-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_add_mail_req_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleformsubmission',
            name='mail_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('progress', 'Progress'), ('cancel', 'Cancel'), ('done', 'Done')], db_column='mail_status', default='pending', max_length=32),
        ),
    ]
