# Generated by Django 5.2.3 on 2025-11-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_googleformsubmission_mail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instverificationstudent',
            name='verification_status',
            field=models.CharField(blank=True, choices=[('IN_PROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('CORRECTION', 'Correction'), ('CANCEL', 'Cancel'), ('DONE', 'Done'), ('DONE_WITH_REMARKS', 'Done With Remarks')], db_column='verification_status', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='status',
            field=models.CharField(blank=True, choices=[('IN_PROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('CORRECTION', 'Correction'), ('CANCEL', 'Cancel'), ('DONE', 'Done'), ('DONE_WITH_REMARKS', 'Done With Remarks')], db_column='status', max_length=20, null=True),
        ),
    ]
