# Generated by Django 5.2.3 on 2025-11-26 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_instverificationstudent_verification_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='enrollment',
            field=models.ForeignKey(blank=True, db_column='enrollment_id', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='verifications', to='api.enrollment'),
        ),
    ]
