# Generated by Django 5.2.3 on 2025-11-27 09:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_verification_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='date',
        ),
        migrations.AddField(
            model_name='verification',
            name='doc_rec_date',
            field=models.DateField(db_column='doc_rec_date', default=django.utils.timezone.now, verbose_name='Doc Record Date'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='eca_status',
            field=models.CharField(blank=True, choices=[('NOT_SENT', 'Not Sent'), ('SENT', 'Sent'), ('FAILED', 'Failed')], db_column='eca_status', max_length=20, null=True),
        ),
    ]
