# Generated by Django 5.2.3 on 2025-12-01 06:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_verification_date_verification_doc_rec_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='verification',
            name='idx_verification_enrollment',
        ),
        migrations.RemoveIndex(
            model_name='verification',
            name='idx_verif_sec_enroll',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='second_enrollment',
        ),
        migrations.AddField(
            model_name='verification',
            name='enrollment_no',
            field=models.CharField(blank=True, db_column='enrollment_no', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='verification',
            name='second_enrollment_id',
            field=models.CharField(blank=True, db_column='second_enrollment_id', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(fields=['enrollment_no'], name='idx_verification_enrollment'),
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(fields=['second_enrollment_id'], name='idx_verif_sec_enroll'),
        ),
    ]
