# Generated by Django 5.2.3 on 2025-12-02 04:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_remove_verification_idx_verification_enrollment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='backlog_count',
            field=models.SmallIntegerField(blank=True, db_column='no_of_backlog', null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='dg_count',
            field=models.SmallIntegerField(blank=True, db_column='no_of_degree', null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='doc_rec_date',
            field=models.DateField(db_column='doc_rec_date', verbose_name='Doc Record Date'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='eca_ref_no',
            field=models.CharField(blank=True, db_column='eca_ref_no', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='eca_required',
            field=models.BooleanField(blank=True, db_column='eca_required', null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='eca_status',
            field=models.CharField(blank=True, choices=[('NOT_SENT', 'Not Sent'), ('SENT', 'Sent'), ('FAILED', 'Failed')], db_column='eca_status', default='NOT_SENT', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='enrollment_no',
            field=models.CharField(blank=True, db_column='enrollment_no', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='final_no',
            field=models.CharField(blank=True, db_column='final_no', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='last_resubmit_status',
            field=models.CharField(blank=True, db_column='last_resubmit_status', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='mail_status',
            field=models.CharField(blank=True, choices=[('NOT_SENT', 'Not Sent'), ('SENT', 'Sent'), ('FAILED', 'Failed')], db_column='mail_send_status', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='moi_count',
            field=models.SmallIntegerField(blank=True, db_column='no_of_moi', null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='ms_count',
            field=models.SmallIntegerField(blank=True, db_column='no_of_marksheet', null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='pay_rec_no',
            field=models.CharField(blank=True, db_column='pay_rec_no', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='second_enrollment_id',
            field=models.CharField(blank=True, db_column='second_enrollment_id', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='status',
            field=models.CharField(blank=True, choices=[('IN_PROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('CORRECTION', 'Correction'), ('CANCEL', 'Cancel'), ('DONE', 'Done'), ('DONE_WITH_REMARKS', 'Done With Remarks')], db_column='status', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='student_name',
            field=models.CharField(blank=True, db_column='student_name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='tr_count',
            field=models.SmallIntegerField(blank=True, db_column='no_of_transcript', null=True),
        ),
        migrations.AddConstraint(
            model_name='verification',
            constraint=models.UniqueConstraint(condition=models.Q(('doc_rec__isnull', False)), fields=('doc_rec',), name='unique_verification_doc_rec'),
        ),
    ]
