# Generated by Django 5.2.3 on 2025-12-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_add_unique_constraint_verification_doc_rec'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvocationMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('convocation_no', models.IntegerField(db_column='convocation_no', unique=True)),
                ('convocation_title', models.CharField(blank=True, db_column='convocation_title', max_length=255, null=True)),
                ('convocation_date', models.DateField(db_column='convocation_date')),
                ('month_year', models.CharField(blank=True, db_column='month_year', max_length=20, null=True)),
            ],
            options={
                'db_table': 'convocation_master',
                'ordering': ['-convocation_date'],
                'indexes': [models.Index(fields=['convocation_no'], name='idx_conv_no'), models.Index(fields=['convocation_date'], name='idx_conv_date')],
            },
        ),
        migrations.CreateModel(
            name='StudentDegree',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dg_sr_no', models.CharField(blank=True, db_column='dg_sr_no', db_index=True, max_length=100, null=True)),
                ('enrollment_no', models.CharField(db_column='enrollment_no', db_index=True, max_length=50)),
                ('student_name_dg', models.CharField(blank=True, db_column='student_name_dg', max_length=255, null=True)),
                ('dg_address', models.TextField(blank=True, db_column='dg_address', null=True)),
                ('institute_name_dg', models.CharField(blank=True, db_column='institute_name_dg', max_length=255, null=True)),
                ('degree_name', models.CharField(blank=True, db_column='degree_name', max_length=255, null=True)),
                ('specialisation', models.CharField(blank=True, db_column='specialisation', max_length=255, null=True)),
                ('seat_last_exam', models.CharField(blank=True, db_column='seat_last_exam', max_length=100, null=True)),
                ('last_exam_month', models.CharField(blank=True, db_column='last_exam_month', max_length=50, null=True)),
                ('last_exam_year', models.IntegerField(blank=True, db_column='last_exam_year', null=True)),
                ('class_obtain', models.CharField(blank=True, db_column='class_obtain', max_length=100, null=True)),
                ('course_language', models.CharField(blank=True, db_column='course_language', max_length=50, null=True)),
                ('dg_rec_no', models.CharField(blank=True, db_column='dg_rec_no', max_length=100, null=True)),
                ('dg_gender', models.CharField(blank=True, db_column='dg_gender', max_length=20, null=True)),
                ('convocation_no', models.IntegerField(blank=True, db_column='convocation_no', db_index=True, null=True)),
            ],
            options={
                'db_table': 'student_degree',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['enrollment_no'], name='idx_stdg_enroll'), models.Index(fields=['dg_sr_no'], name='idx_stdg_sr_no'), models.Index(fields=['convocation_no'], name='idx_stdg_conv_no'), models.Index(fields=['last_exam_year'], name='idx_stdg_exam_year')],
            },
        ),
    ]
