# Generated by Django 5.2.3 on 2025-12-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_update_transcript_request_not_null_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptrequest',
            name='enrollment_no',
            field=models.CharField(db_column='enrollment_no', max_length=64),
        ),
        migrations.AlterField(
            model_name='transcriptrequest',
            name='institute_name',
            field=models.CharField(db_column='institute_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='transcriptrequest',
            name='mail_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('progress', 'In Progress'), ('done', 'Done')], db_column='mail_status', default='pending', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='transcriptrequest',
            name='pdf_generate',
            field=models.CharField(blank=True, db_column='pdf_generate', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='transcriptrequest',
            name='request_ref_no',
            field=models.CharField(blank=True, db_column='trn_reqest_ref_no', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='transcriptrequest',
            name='student_name',
            field=models.CharField(db_column='student_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='transcriptrequest',
            name='submit_mail',
            field=models.CharField(blank=True, db_column='submit_mail', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transcriptrequest',
            name='tr_request_no',
            field=models.BigIntegerField(db_column='tr_request_no'),
        ),
        migrations.AlterField(
            model_name='transcriptrequest',
            name='transcript_receipt',
            field=models.CharField(blank=True, db_column='trnscript_receipt', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transcriptrequest',
            name='transcript_remark',
            field=models.TextField(blank=True, db_column='transcript_remark', null=True),
        ),
    ]
