# Generated by Django 5.2.3 on 2025-12-05 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_add_fts_search_vectors'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='docrec',
            name='docrec_search_idx',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='enrollment_search_idx',
        ),
        migrations.RemoveIndex(
            model_name='googleformsubmission',
            name='googleform_search_idx',
        ),
        migrations.RemoveIndex(
            model_name='instverificationmain',
            name='instverif_search_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentdegree',
            name='studentdegree_search_idx',
        ),
        migrations.RemoveIndex(
            model_name='transcriptrequest',
            name='transcriptrequest_search_idx',
        ),
        migrations.RemoveIndex(
            model_name='verification',
            name='verification_search_idx',
        ),
    ]
