# Generated by Django 5.2.3 on 2025-12-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_add_sandwich_to_leaveallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdegree',
            name='dg_contact',
            field=models.CharField(blank=True, db_column='dg_contact', max_length=15, null=True),
        ),
    ]
