# Generated by Django 5.2.3 on 2025-12-09 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_studentdegree_dg_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_item',
                'ordering': ['item_name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryInward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inward_date', models.DateField()),
                ('qty', models.IntegerField()),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inward_entries', to='api.inventoryitem')),
            ],
            options={
                'db_table': 'inventory_inward',
                'ordering': ['-inward_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryOutward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outward_date', models.DateField()),
                ('qty', models.IntegerField()),
                ('receiver', models.CharField(max_length=255)),
                ('received_qty', models.IntegerField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outward_entries', to='api.inventoryitem')),
            ],
            options={
                'db_table': 'inventory_outward',
                'ordering': ['-outward_date', '-created_at'],
            },
        ),
    ]
