# Generated by Django 5.2.3 on 2025-12-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_inventoryitem_inventoryinward_inventoryoutward'),
    ]

    operations = [
        migrations.CreateModel(
            name='InwardRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inward_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('inward_date', models.DateField()),
                ('inward_type', models.CharField(choices=[('Gen', 'General'), ('Exam', 'Examination'), ('Enr', 'Enrollment'), ('Can', 'Cancellation'), ('Doc', 'Document')], max_length=20)),
                ('inward_from', models.CharField(max_length=255, verbose_name='Sender')),
                ('rec_type', models.CharField(choices=[('Inward', 'Inward'), ('External', 'External')], max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inward Register',
                'verbose_name_plural': 'Inward Registers',
                'db_table': 'inward_register',
                'ordering': ['-inward_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutwardRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outward_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('outward_date', models.DateField()),
                ('outward_type', models.CharField(choices=[('Gen', 'General'), ('Exam', 'Examination'), ('Enr', 'Enrollment'), ('Can', 'Cancellation'), ('Doc', 'Document')], max_length=20)),
                ('outward_to', models.CharField(max_length=255, verbose_name='Receiver')),
                ('send_type', models.CharField(choices=[('Outward', 'Outward'), ('External', 'External')], max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Outward Register',
                'verbose_name_plural': 'Outward Registers',
                'db_table': 'outward_register',
                'ordering': ['-outward_date', '-created_at'],
            },
        ),
    ]
