# Generated by Django 5.2.3 on 2025-12-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_inwardregister_outwardregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inwardregister',
            name='rec_type',
            field=models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], max_length=20),
        ),
        migrations.AlterField(
            model_name='outwardregister',
            name='send_type',
            field=models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], max_length=20),
        ),
    ]
