# Generated by Django 5.2.3 on 2025-12-10 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_inwardregister_rec_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empprofile',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='LeaveBalanceSnapshot',
        ),
    ]
