# Generated by Django 5.2.3 on 2025-12-10 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_empprofile_options_delete_leavebalancesnapshot'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empprofile',
            table='api_empprofile',
        ),
    ]
