# Generated by GitHub Copilot GPT-5.1-Codex (Preview)
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_alter_empprofile_table'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "ALTER TABLE student_degree "
                "DROP CONSTRAINT IF EXISTS student_degree_enrollment_no_key"
            ),
            reverse_sql=(
                "ALTER TABLE student_degree "
                "ADD CONSTRAINT student_degree_enrollment_no_key UNIQUE (enrollment_no)"
            ),
        ),
        migrations.AddConstraint(
            model_name='studentdegree',
            constraint=models.UniqueConstraint(
                fields=['dg_sr_no'],
                name='uniq_student_degree_dg_sr_no',
            ),
        ),
    ]
