# Generated by Django 5.1.6 on 2025-12-16 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_fix_degree_unique_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fee_type',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('UPI', 'UPI')], max_length=8)),
                ('receipt_no', models.CharField(editable=False, max_length=32, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_register_entries', to=settings.AUTH_USER_MODEL)),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_entries', to='api.feetype')),
            ],
            options={
                'db_table': 'cash_register',
                'ordering': ['-date', '-receipt_no'],
            },
        ),
    ]
