# Generated by Django 5.2.3 on 2025-12-17 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_cashregister_rec_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashregister',
            options={'ordering': ['-date', '-rec_ref', '-rec_no']},
        ),
    ]
