# Generated by Django 5.1.6 on 2025-12-30 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_receipt_receiptitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='receiptitem',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='fee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.feetype'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='receipt_no_full',
            field=models.CharField(db_index=True, editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_mode',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='rec_no',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='rec_ref',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_no_full',
            field=models.CharField(db_index=True, editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='fee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.feetype'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(fields=('rec_ref', 'rec_no'), name='uniq_receipt_series_number'),
        ),
    ]
