# Generated by Django 5.1.6 on 2025-12-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_remove_receipt_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
