# Generated by Django 5.2.3 on 2026-01-17 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_remove_receipt_unique_constraints'),
        ('api', '0063_alter_receipt_payment_mode'),
    ]

    operations = [
    ]
