# Generated by Django 5.1.6 on 2026-01-19 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_merge_20260117_1440'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashOnHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('system_cash', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_deposit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_expense', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expected_cash', models.DecimalField(decimal_places=2, max_digits=14)),
                ('physical_cash', models.DecimalField(decimal_places=2, max_digits=14)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cash_on_hand',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CashOutward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('txn_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('EXPENSE', 'Expense')], max_length=10)),
                ('ref_no', models.CharField(blank=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cash_outward',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CashOnHandItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.PositiveIntegerField()),
                ('is_coin', models.BooleanField(default=False)),
                ('qty', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cash_on_hand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.cashonhand')),
            ],
            options={
                'db_table': 'cash_on_hand_item',
                'ordering': ['-denomination'],
                'unique_together': {('cash_on_hand', 'denomination', 'is_coin')},
            },
        ),
    ]
