# Generated by Django 5.2.3 on 2026-01-20 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_cashonhand_cashoutward_cashonhanditem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeesLedger',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('receipt_no', models.CharField(db_index=True, max_length=30, unique=True)),
                ('receipt_date', models.DateField(db_index=True)),
                ('term', models.CharField(help_text='e.g. 1st Term, 2nd Term, Extension-1, Exam Fee', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_student_fees', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(db_column='enrollment_no', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='fee_ledger', to='api.enrollment', to_field='enrollment_no')),
            ],
            options={
                'db_table': 'student_fees_ledger',
                'ordering': ['-receipt_date', '-id'],
                'indexes': [models.Index(fields=['enrollment'], name='student_fee_enrollm_b143d7_idx'), models.Index(fields=['receipt_date'], name='student_fee_receipt_515104_idx'), models.Index(fields=['term'], name='student_fee_term_cdd263_idx')],
            },
        ),
    ]
