# Generated by Django 5.2.3 on 2026-01-22 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_studentfeesledger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InwardRegister',
        ),
        migrations.DeleteModel(
            name='OutwardRegister',
        ),
    ]
