# Generated by Django 5.2.3 on 2026-01-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_dashboardpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='eca_status',
            field=models.CharField(blank=True, choices=[('NOT_SENT', 'Not Sent'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('ACCEPTED', 'Accepted')], db_column='eca_status', default='NOT_SENT', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='mail_status',
            field=models.CharField(blank=True, choices=[('NOT_SENT', 'Not Sent'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('ACCEPTED', 'Accepted')], db_column='mail_send_status', max_length=255, null=True),
        ),
    ]
