# Generated by Django 5.2.3 on 2026-01-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_alter_verification_eca_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='cancel',
            field=models.BooleanField(blank=True, db_column='cancel', default=None, help_text='If true, admission is cancelled. If null or false, active.', null=True),
        ),
    ]
