# Generated by Django 5.2.3 on 2026-01-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_enrollment_cancel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docrec',
            name='doc_rec_remark',
        ),
        migrations.RemoveField(
            model_name='eca',
            name='eca_remark',
        ),
        migrations.RemoveField(
            model_name='migrationrecord',
            name='doc_rec_remark',
        ),
        migrations.RemoveField(
            model_name='provisionalrecord',
            name='doc_rec_remark',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='doc_rec_remark',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='remark',
        ),
        migrations.AddField(
            model_name='docrec',
            name='doc_remark',
            field=models.CharField(blank=True, db_column='doc_remark', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eca',
            name='doc_remark',
            field=models.TextField(blank=True, db_column='doc_remark', null=True),
        ),
        migrations.AddField(
            model_name='migrationrecord',
            name='doc_remark',
            field=models.CharField(blank=True, db_column='doc_remark', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provisionalrecord',
            name='doc_remark',
            field=models.CharField(blank=True, db_column='doc_remark', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='verification',
            name='doc_remark',
            field=models.TextField(blank=True, db_column='doc_remark', null=True),
        ),
    ]
