# Generated by Django 5.2.3 on 2026-02-07 03:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_remove_docrec_doc_rec_remark_remove_eca_eca_remark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionCancel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cancel_date', models.DateField(default=django.utils.timezone.now)),
                ('student_name', models.CharField(max_length=100)),
                ('inward_no', models.CharField(blank=True, max_length=50, null=True)),
                ('inward_date', models.DateField(blank=True, null=True)),
                ('outward_no', models.CharField(blank=True, max_length=50, null=True)),
                ('outward_date', models.DateField(blank=True, null=True)),
                ('can_remark', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CANCELLED', 'Cancelled'), ('REVOKED', 'Revoked')], default='CANCELLED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation', to='api.enrollment')),
            ],
            options={
                'db_table': 'admission_cancel',
                'ordering': ['-cancel_date', '-id'],
            },
        ),
    ]
