# Generated by Django 5.2.3 on 2026-02-11 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_admissioncancel'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstLetterStudent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sr_no', models.PositiveIntegerField(blank=True, db_column='sr_no', null=True)),
                ('enrollment_no_text', models.CharField(blank=True, db_column='enrollment_no_text', max_length=64, null=True)),
                ('student_name', models.CharField(blank=True, db_column='student_name', max_length=255, null=True)),
                ('type_of_credential', models.CharField(blank=True, db_column='type_of_credential', max_length=50, null=True)),
                ('month_year', models.CharField(blank=True, db_column='month_year', max_length=20, null=True)),
                ('verification_status', models.CharField(blank=True, db_column='verification_status', max_length=100, null=True)),
                ('iv_degree_name', models.CharField(blank=True, db_column='iv_degree_name', max_length=255, null=True)),
                ('doc_rec', models.ForeignKey(blank=True, db_column='doc_rec_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inst_verification_students', to='api.docrec', to_field='doc_rec_id')),
                ('enrollment', models.ForeignKey(blank=True, db_column='enrollment_no', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inst_verification_students', to='api.enrollment', to_field='enrollment_no')),
                ('institute', models.ForeignKey(blank=True, db_column='institute_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inst_verification_students', to='api.institute')),
                ('main_course', models.ForeignKey(blank=True, db_column='main_course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inst_verification_students', to='api.mainbranch', to_field='maincourse_id')),
                ('sub_course', models.ForeignKey(blank=True, db_column='sub_course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inst_verification_students', to='api.subbranch', to_field='subcourse_id')),
            ],
            options={
                'db_table': 'inst_verification_student',
            },
        ),
        migrations.RenameModel(
            old_name='InstVerificationMain',
            new_name='InstLetterMain',
        ),
        migrations.RemoveField(
            model_name='instverificationstudent',
            name='doc_rec',
        ),
        migrations.RemoveField(
            model_name='instverificationstudent',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='instverificationstudent',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='instverificationstudent',
            name='main_course',
        ),
        migrations.RemoveField(
            model_name='instverificationstudent',
            name='sub_course',
        ),
        migrations.RemoveField(
            model_name='inventoryinward',
            name='item',
        ),
        migrations.RemoveField(
            model_name='inventoryoutward',
            name='item',
        ),
        migrations.DeleteModel(
            name='InwardRegister',
        ),
        migrations.DeleteModel(
            name='OutwardRegister',
        ),
        migrations.DeleteModel(
            name='InstVerificationStudent',
        ),
        migrations.DeleteModel(
            name='InventoryInward',
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
        migrations.DeleteModel(
            name='InventoryOutward',
        ),
        migrations.AddIndex(
            model_name='instletterstudent',
            index=models.Index(fields=['doc_rec'], name='idx_ivs_doc_rec'),
        ),
        migrations.AddIndex(
            model_name='instletterstudent',
            index=models.Index(fields=['enrollment'], name='idx_ivs_enrollment'),
        ),
        migrations.AddIndex(
            model_name='instletterstudent',
            index=models.Index(fields=['institute'], name='idx_ivs_institute'),
        ),
    ]
