# Generated by Django 5.2.3 on 2026-02-11 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_instletterstudent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_item',
                'ordering': ['item_name'],
            },
        ),
        migrations.CreateModel(
            name='InwardRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inward_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('inward_date', models.DateField()),
                ('inward_type', models.CharField(choices=[('Gen', 'General'), ('Exam', 'Examination'), ('Enr', 'Enrollment'), ('Can', 'Cancellation'), ('Doc', 'Document')], max_length=20)),
                ('inward_from', models.CharField(max_length=255, verbose_name='Sender')),
                ('rec_type', models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inward Register',
                'verbose_name_plural': 'Inward Registers',
                'db_table': 'inward_register',
                'ordering': ['-inward_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutwardRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outward_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('outward_date', models.DateField()),
                ('outward_type', models.CharField(choices=[('Gen', 'General'), ('Exam', 'Examination'), ('Enr', 'Enrollment'), ('Can', 'Cancellation'), ('Doc', 'Document')], max_length=20)),
                ('outward_to', models.CharField(max_length=255, verbose_name='Receiver')),
                ('send_type', models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Outward Register',
                'verbose_name_plural': 'Outward Registers',
                'db_table': 'outward_register',
                'ordering': ['-outward_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryInward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inward_date', models.DateField()),
                ('qty', models.IntegerField()),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inward_entries', to='api.inventoryitem')),
            ],
            options={
                'db_table': 'inventory_inward',
                'ordering': ['-inward_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryOutward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outward_date', models.DateField()),
                ('qty', models.IntegerField()),
                ('receiver', models.CharField(max_length=255)),
                ('received_qty', models.IntegerField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outward_entries', to='api.inventoryitem')),
            ],
            options={
                'db_table': 'inventory_outward',
                'ordering': ['-outward_date', '-created_at'],
            },
        ),
    ]
