# backend/api/migrations/0077_remove_instletterstudent_idx_ivs_institute_and_more.py
# Generated by Django 5.2.3 on 2026-02-12 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_move_study_mode_to_student'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='instletterstudent',
            name='idx_ivs_institute',
        ),
        migrations.RemoveField(
            model_name='instletterstudent',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='instletterstudent',
            name='main_course',
        ),
        migrations.RemoveField(
            model_name='instletterstudent',
            name='sub_course',
        ),
    ]
