# Generated by Django 5.1.6 on 2026-02-18 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_remove_instletterstudent_idx_ivs_institute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCTVExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_year_session', models.CharField(max_length=10)),
                ('exam_date', models.DateField()),
                ('exam_time', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=10)),
                ('subject_code', models.CharField(max_length=50)),
                ('subject_name', models.CharField(max_length=255)),
                ('total_students', models.IntegerField(default=0)),
                ('institute_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='CCTVExamCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('session', models.CharField(choices=[('A', 'A Session'), ('B', 'B Session'), ('C', 'C Session'), ('D', 'D Session')], max_length=1)),
                ('no_of_cd', models.IntegerField()),
                ('start_number', models.IntegerField(blank=True, null=True)),
                ('end_number', models.IntegerField(blank=True, null=True)),
                ('start_label', models.CharField(blank=True, max_length=20, null=True)),
                ('end_label', models.CharField(blank=True, max_length=20, null=True)),
                ('objection_found', models.BooleanField(default=False)),
                ('no_of_objection_cd', models.IntegerField(default=0)),
                ('cc_start_number', models.IntegerField(blank=True, null=True)),
                ('cc_end_number', models.IntegerField(blank=True, null=True)),
                ('cc_start_label', models.CharField(blank=True, max_length=20)),
                ('cc_end_label', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centres', to='api.cctvexam')),
            ],
            options={
                'unique_together': {('exam', 'place', 'session')},
            },
        ),
        migrations.CreateModel(
            name='CCTVDVD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('label', models.CharField(max_length=20)),
                ('objection_found', models.BooleanField(default=False)),
                ('cc_number', models.IntegerField(blank=True, null=True)),
                ('cc_label', models.CharField(blank=True, max_length=20)),
                ('sent_to_college', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dvds', to='api.cctvexamcentre')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='CCTVOutward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outward_no', models.CharField(max_length=50, unique=True)),
                ('outward_date', models.DateField()),
                ('cc_start_label', models.CharField(max_length=20)),
                ('cc_end_label', models.CharField(max_length=20)),
                ('no_of_cc', models.IntegerField()),
                ('return_received', models.BooleanField(default=False)),
                ('case_found', models.BooleanField(default=False)),
                ('case_type', models.CharField(blank=True, choices=[('CCTV', 'CCTV'), ('Physical', 'Physical')], max_length=20, null=True)),
                ('case_details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cctvexamcentre')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cctvexam')),
            ],
            options={
                'ordering': ['-outward_date'],
            },
        ),
    ]
