# Generated by Django 5.2.3 on 2026-02-19 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_cctvexam_cctvexamcentre_cctvdvd_cctvoutward'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cctvexam',
            old_name='total_students',
            new_name='no_of_students',
        ),
        migrations.RenameField(
            model_name='cctvexam',
            old_name='semester',
            new_name='sem',
        ),
        migrations.AddField(
            model_name='cctvexam',
            name='raw_row',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='cctvexam',
            name='exam_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cctvexam',
            name='exam_year_session',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cctvexam',
            name='institute_remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cctvexam',
            name='subject_name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='CCTVCentreEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('place', models.CharField(max_length=100)),
                ('no_of_cd', models.IntegerField()),
                ('start_number', models.IntegerField(blank=True, null=True)),
                ('end_number', models.IntegerField(blank=True, null=True)),
                ('start_label', models.CharField(blank=True, max_length=20, null=True)),
                ('end_label', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cctvexam')),
            ],
        ),
        migrations.AlterField(
            model_name='cctvdvd',
            name='centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dvds', to='api.cctvcentreentry'),
        ),
        migrations.AlterField(
            model_name='cctvoutward',
            name='centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cctvcentreentry'),
        ),
        migrations.DeleteModel(
            name='CCTVExamCentre',
        ),
    ]
