# Generated by Django 5.2.3 on 2026-02-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_rename_total_students_cctvexam_no_of_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cctvcentreentry',
            name='cc_end_label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cctvcentreentry',
            name='cc_start_label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cctvcentreentry',
            name='cc_total',
            field=models.IntegerField(default=0),
        ),
    ]
