# Generated by Django 5.1.6 on 2026-02-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_migrate_studentfeesledger_enrollment_fk'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER INDEX IF EXISTS student_fee_enrollm_b143d7_idx RENAME TO student_fee_enrollm_b4acb9_idx;",
            reverse_sql="ALTER INDEX IF EXISTS student_fee_enrollm_b4acb9_idx RENAME TO student_fee_enrollm_b143d7_idx;",
        ),
        migrations.RemoveField(
            model_name='cctvoutward',
            name='centre',
        ),
        migrations.RemoveField(
            model_name='cctvoutward',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='cctvoutward',
            name='no_of_cc',
        ),
        migrations.AddField(
            model_name='cctvoutward',
            name='cctv_record_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cctvoutward',
            name='centre_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cctvoutward',
            name='college_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cctvoutward',
            name='exam_on',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cctvoutward',
            name='last_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cctvoutward',
            name='no_of_dvd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cctvoutward',
            name='no_of_report',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cctvoutward',
            name='remark',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cctvoutward',
            name='cc_end_label',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cctvoutward',
            name='cc_start_label',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cctvoutward',
            name='outward_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cctvoutward',
            name='outward_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
