# Generated by Django 5.1.6 on 2026-02-26 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_rename_student_fee_enrollm_b143d7_idx_student_fee_enrollm_b4acb9_idx'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER INDEX IF EXISTS student_fee_enrollm_b143d7_idx RENAME TO student_fee_enrollm_b4acb9_idx;",
            reverse_sql="ALTER INDEX IF EXISTS student_fee_enrollm_b4acb9_idx RENAME TO student_fee_enrollm_b143d7_idx;",
        ),
    ]
