# Generated by Django 5.2.3 on 2026-02-26 14:10

from django.db import migrations


def set_pdf_cancel(apps, schema_editor):
    TranscriptRequest = apps.get_model("api", "TranscriptRequest")
    cancel_values = ["cancel", "cancelled", "canceled"]
    for value in cancel_values:
        TranscriptRequest.objects.filter(mail_status__iexact=value).exclude(pdf_generate="Cancel").update(
            pdf_generate="Cancel"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0089_rename_student_fee_enrollm_b143d7_idx_student_fee_enrollm_b4acb9_idx"),
    ]

    operations = [
        migrations.RunPython(set_pdf_cancel, migrations.RunPython.noop),
    ]
