# Generated by Django 5.2.3 on 2026-02-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_set_transcript_pdf_cancel_on_mail_cancel'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name='studentfeesledger',
                    new_name='student_fee_enrollm_b4acb9_idx',
                    old_name='student_fee_enrollm_b143d7_idx',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "DO $$ BEGIN "
                        "IF to_regclass('public.student_fee_enrollm_b143d7_idx') IS NOT NULL THEN "
                        "ALTER INDEX student_fee_enrollm_b143d7_idx RENAME TO student_fee_enrollm_b4acb9_idx; "
                        "END IF; "
                        "END $$;"
                    ),
                    reverse_sql=(
                        "DO $$ BEGIN "
                        "IF to_regclass('public.student_fee_enrollm_b4acb9_idx') IS NOT NULL THEN "
                        "ALTER INDEX student_fee_enrollm_b4acb9_idx RENAME TO student_fee_enrollm_b143d7_idx; "
                        "END IF; "
                        "END $$;"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='transcriptrequest',
            name='mail_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('progress', 'In Progress'), ('cancel', 'Cancel'), ('done', 'Done')], db_column='mail_status', default='pending', max_length=32, null=True),
        ),
    ]
