# Generated by Django 5.2.3 on 2026-02-27 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_rename_student_fee_enrollm_b143d7_idx_student_fee_enrollm_b4acb9_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_mime', models.CharField(blank=True, max_length=100, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('hide_for_sender', models.BooleanField(default=False)),
                ('hide_for_receiver', models.BooleanField(default=False)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['createdat'],
                'indexes': [models.Index(fields=['from_user', 'to_user', 'createdat'], name='chat_messag_from_us_fb330f_idx'), models.Index(fields=['to_user', 'from_user', 'createdat'], name='chat_messag_to_user_e0b261_idx')],
            },
        ),
    ]
