# backend/api/migrations/0093_chatmessage_downloaded_at_chatmessage_file_delivered_and_more.py
# Generated by Django 5.1.6 on 2026-02-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file_downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
