# Generated by Django 5.1.6 on 2026-02-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_chatmessage_downloaded_at_chatmessage_file_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
