# backend/api/migrations/0100_cctvoutward_add_note.py
# Generated by Django 5.1.6 on 2026-03-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_studentprofile_father_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cctvoutward',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
