# backend/api/migrations/0101_cctvoutward_add_report_nos.py
# Generated by Django 5.1.6 on 2026-03-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_cctvoutward_add_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cctvoutward',
            name='cc_end_label',
        ),
        migrations.RemoveField(
            model_name='cctvoutward',
            name='remark',
        ),
        migrations.AddField(
            model_name='cctvoutward',
            name='rep_nos',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cctvoutward',
            name='cc_start_label',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
