# backend/api/migrations/0102_inwardregister_extra_data_outwardregister_extra_data_and_more.py
# Generated by Django 5.1.6 on 2026-03-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_cctvoutward_add_report_nos'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwardregister',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outwardregister',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inwardregister',
            name='rec_type',
            field=models.CharField(blank=True, choices=[('Internal', 'Internal'), ('External', 'External')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='outwardregister',
            name='send_type',
            field=models.CharField(blank=True, choices=[('Internal', 'Internal'), ('External', 'External')], default='', max_length=20),
        ),
    ]
