# Generated by Django 5.1.6 on 2026-03-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_inwardregister_extra_data_outwardregister_extra_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cctvoutward',
            name='receive_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cctvoutward',
            name='course',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='cctvoutward',
            name='semester',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
