# Generated by Django 5.1.6 on 2026-03-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_cctvoutward_receive_date_course_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCTVCopyCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(blank=True, default='', max_length=200)),
                ('course', models.CharField(blank=True, default='', max_length=120)),
                ('semester', models.CharField(blank=True, default='', max_length=30)),
                ('dvd_no', models.CharField(blank=True, default='', max_length=200)),
                ('report_no', models.CharField(blank=True, default='', max_length=200)),
                ('no_of_student', models.PositiveIntegerField(default=0)),
                ('remark', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outward', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='copy_cases', to='api.cctvoutward')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
