# Generated by Django 5.1.6 on 2026-03-19 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_cctvcopycase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentOutward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outward_no', models.CharField(editable=False, max_length=50, unique=True)),
                ('outward_date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_outwards_generated', to=settings.AUTH_USER_MODEL)),
                ('receiver_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_outwards_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assessment_outward',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('exam_name', models.CharField(max_length=255)),
                ('examiner_name', models.CharField(max_length=255)),
                ('dummy_number', models.CharField(max_length=100)),
                ('total_answer_sheet', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Outward', 'Outward'), ('PartiallyReceived', 'Partially Received'), ('Received', 'Received')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_entries_added', to=settings.AUTH_USER_MODEL)),
                ('outward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='api.assessmentoutward')),
            ],
            options={
                'db_table': 'assessment_entry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentOutwardDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_status', models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received')], default='Pending', max_length=20)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('receive_remark', models.TextField(blank=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outward_details', to='api.assessmententry')),
                ('outward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api.assessmentoutward')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assessment_outward_details',
            },
        ),
    ]
