# backend/api/migrations/0109_assessment_return_flow_fields.py
# Generated by Django 5.1.6 on 2026-03-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_move_schedule_cctv_to_exam'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentoutwarddetails',
            name='return_remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessmentoutwarddetails',
            name='return_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Returned', 'Returned')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='assessmentoutwarddetails',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentoutwarddetails',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmententry',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Outward', 'Outward'), ('PartiallyReceived', 'Partially Received'), ('Received', 'Received'), ('Returned', 'Returned'), ('FinalReceived', 'Final Received')], default='Pending', max_length=50),
        ),
    ]
