# Generated by Django 5.1.6 on 2026-03-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_assessment_return_flow_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentoutwarddetails',
            name='return_outward_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
