# Generated by Django 5.1.6 on 2026-03-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_assessment_return_outward_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmententry',
            name='remark',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assessmententry',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Outward', 'Outward'), ('PartiallyReceived', 'Partially Received'), ('Received', 'Received'), ('Returned', 'Returned'), ('Completed', 'Completed'), ('FinalReceived', 'Final Received')], default='Pending', max_length=50),
        ),
    ]
