# backend/api/migrations/0112_assessment_entry_remark_default.py
# Generated by Django 5.1.6 on 2026-03-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_assessment_entry_remark_and_completed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmententry',
            name='remark',
            field=models.TextField(blank=True, default=''),
        ),
    ]
