# backend/api/migrations/0115_assessmentoutwarddetails_final_receive_remark_and_more.py
# Generated by Django 5.1.6 on 2026-03-19 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_assessment_remove_final_received'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentoutwarddetails',
            name='final_receive_remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessmentoutwarddetails',
            name='final_receive_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='assessmentoutwarddetails',
            name='final_received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_final_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentoutwarddetails',
            name='final_received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmententry',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Outward', 'Outward'), ('InProgress', 'In Progress'), ('PartiallyReceived', 'Partially Received'), ('Received', 'Received'), ('Returned', 'Returned'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
