# Generated by Django 5.1.6 on 2026-03-20 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_assessmentoutwarddetails_final_receive_remark_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentoutwarddetails',
            name='work_remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessmentoutwarddetails',
            name='work_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'In Progress'), ('Done', 'Done')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='assessmentoutwarddetails',
            name='work_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_work_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentoutwarddetails',
            name='work_updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentoutwarddetails',
            unique_together={('outward', 'entry')},
        ),
    ]
