# Generated by Django 5.1.6 on 2026-03-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_work_status_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cctvexam',
            name='course',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cctvexam',
            name='subject_code',
            field=models.CharField(max_length=100),
        ),
    ]
