# Generated by GitHub Copilot on 2026-04-04

from django.db import migrations, models


def copy_existing_deposit_date_to_cash_date(apps, schema_editor):
    CashOutward = apps.get_model("api", "CashOutward")
    CashOutward.objects.filter(txn_type="DEPOSIT", cash_date__isnull=True).update(cash_date=models.F("date"))


def clear_cash_date_for_rollback(apps, schema_editor):
    CashOutward = apps.get_model("api", "CashOutward")
    CashOutward.objects.filter(txn_type="DEPOSIT").update(cash_date=None)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0117_alter_cctvexam_course_alter_cctvexam_subject_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashoutward",
            name="cash_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(copy_existing_deposit_date_to_cash_date, clear_cash_date_for_rollback),
    ]