# Generated by Django 5.1.6 on 2026-04-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_migrationrecord_cancel_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cctvcentreentry',
            name='session',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H')], max_length=1),
        ),
    ]
