# Generated by Codex on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0120_alter_cctvcentreentry_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cctvcentreentry",
            name="session",
            field=models.CharField(
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                    ("G", "G"),
                    ("H", "H"),
                    ("I", "I"),
                    ("J", "J"),
                    ("K", "K"),
                    ("L", "L"),
                    ("M", "M"),
                    ("N", "N"),
                    ("O", "O"),
                    ("P", "P"),
                ],
                max_length=1,
            ),
        ),
    ]
