# Generated by Gemini

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_extend_cctvcentreentry_session_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instletterstudent',
            name='verification_status',
            field=models.CharField(blank=True, db_column='verification_status', max_length=500, null=True),
        ),
    ]
