# Generated by Django 5.1.6 on 2026-07-06 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_alter_instletterstudent_verification_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InwardRegister',
        ),
        migrations.DeleteModel(
            name='OutwardRegister',
        ),
    ]
