# Generated by Django 5.1.6 on 2026-09-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0128_add_student_register_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cctvexam',
            name='sem',
            field=models.CharField(max_length=50),
        ),
    ]
