# Generated by Django 5.1.6 on 2026-09-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0129_alter_cctvexam_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cctvexam',
            name='record_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
