"""
Assessment System Models

AssessmentEntry  – individual answer-bundle entry added by a user
AssessmentOutward – the outward dispatch document generated by an officer
AssessmentOutwardDetails – per-entry rows inside an outward
"""
from django.db import models
from django.contrib.auth.models import User

__all__ = [
    "AssessmentEntry",
    "AssessmentOutward",
    "AssessmentOutwardDetails",
]


class AssessmentOutward(models.Model):
    """Outward dispatch document that groups assessment entries."""

    STATUS_CHOICES = [
        ("Pending", "Pending"),
        ("Completed", "Completed"),
    ]

    outward_no = models.CharField(max_length=50, unique=True, editable=False)
    outward_date = models.DateField()
    generated_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        related_name="assessment_outwards_generated",
    )
    receiver_user = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        related_name="assessment_outwards_received",
    )
    remarks = models.TextField(blank=True)
    status = models.CharField(
        max_length=20, choices=STATUS_CHOICES, default="Pending"
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "assessment_outward"
        ordering = ["-created_at"]

    def __str__(self):
        return self.outward_no


class AssessmentEntry(models.Model):
    """Individual answer-bundle entry."""

    STATUS_CHOICES = [
        ("Pending", "Pending"),
        ("Outward", "Outward"),
        ("InProgress", "In Progress"),
        ("PartiallyReceived", "Partially Received"),
        ("Received", "Received"),
        ("Returned", "Returned"),
        ("Completed", "Completed"),
    ]

    entry_date = models.DateField()
    exam_name = models.CharField(max_length=255)
    examiner_name = models.CharField(max_length=255)
    dummy_number = models.CharField(max_length=100)
    total_answer_sheet = models.IntegerField()
    remark = models.TextField(blank=True, default="")

    added_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        related_name="assessment_entries_added",
    )
    outward = models.ForeignKey(
        AssessmentOutward,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="entries",
    )
    status = models.CharField(
        max_length=50, choices=STATUS_CHOICES, default="Pending"
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "assessment_entry"
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.dummy_number} – {self.exam_name}"


class AssessmentOutwardDetails(models.Model):
    """Per-entry row within an outward, tracks receive/return/final-receive status."""

    RECEIVE_STATUS_CHOICES = [
        ("Pending", "Pending"),
        ("Received", "Received"),
    ]

    RETURN_STATUS_CHOICES = [
        ("Pending", "Pending"),
        ("Returned", "Returned"),
    ]

    FINAL_RECEIVE_STATUS_CHOICES = [
        ("Pending", "Pending"),
        ("Received", "Received"),
    ]

    outward = models.ForeignKey(
        AssessmentOutward,
        on_delete=models.CASCADE,
        related_name="details",
    )
    entry = models.ForeignKey(
        AssessmentEntry,
        on_delete=models.CASCADE,
        related_name="outward_details",
    )
    receive_status = models.CharField(
        max_length=20, choices=RECEIVE_STATUS_CHOICES, default="Pending"
    )
    received_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="assessment_receipts",
    )
    received_date = models.DateTimeField(null=True, blank=True)
    receive_remark = models.TextField(blank=True)
    return_status = models.CharField(
        max_length=20, choices=RETURN_STATUS_CHOICES, default="Pending"
    )
    returned_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="assessment_returns",
    )
    returned_date = models.DateTimeField(null=True, blank=True)
    return_remark = models.TextField(blank=True)
    return_outward_no = models.CharField(max_length=50, blank=True, default="")
    final_received_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="assessment_final_receipts",
    )
    final_received_date = models.DateTimeField(null=True, blank=True)
    final_receive_remark = models.TextField(blank=True)
    final_receive_status = models.CharField(
        max_length=20, choices=FINAL_RECEIVE_STATUS_CHOICES, default="Pending"
    )

    class Meta:
        db_table = "assessment_outward_details"

    def __str__(self):
        return f"{self.outward.outward_no} – {self.entry.dummy_number}"
