from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import HolidayViewSet, LoginView

# Create the router and register the HolidayViewSet
router = DefaultRouter()
router.register(r'holidays', HolidayViewSet)  # Automatically generates routes for the viewset

urlpatterns = [
    path('', include(router.urls)),  # Includes all the routes generated by the viewset
    path('login/', LoginView.as_view(), name='login'),  # Login endpoint
]
